name = "led-catalog"
pages_build_output_dir = "dist"
compatibility_date = "2024-06-01"

[[kv_namespaces]]
binding = "CATALOG_DB"
id = "4ab62cbc41bc43259dec114a1e7393f9"
preview_id = "178eefa3430545a390a27ccf920fbd20"