name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: led-catalog
          directory: dist
          branch: ${{ github.head_ref || github.ref_name }}
          wranglerVersion: "4.45.1"

      - name: Deploy preview to Netlify
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@v3
        with:
          args: deploy --dir=dist --alias=pr-${{ github.event.number }} --message="Preview deploy for PR #${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy production to Netlify
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: netlify/actions/cli@v3
        with:
          args: deploy --dir=dist --prod --message="Main branch deploy ${GITHUB_SHA}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
